* LITMUS IDL for an SBUS Component

@component-metadata
{
	txt name
	txt description
	keywords ( txt keyword )
	txt designer
	endpoints
	(
		endpoint
		{
			txt name
			^endpoint-type type
			^idl message + response
		}
	)
}

@idl txt
@endpoint-type < #server #client #source #sink >
