@criteria
{
	^map-constraints -
	^interface -
}					

@map-constraints
{
	[ txt cpt-name ]
	[ txt instance-name ]
	[ txt creator ]
	[ txt pub-key ]
	hashes ( txt hash )
	type-hashes ( txt hash )
	keywords ( txt keyword )
	parents ( txt cpt )
	ancestors ( txt cpt )
	flg match-endpoint-names
}

@interface
(
	endpoint
	{
		[ txt name ]
		^endpoint-type type
		txt msg-hash + reply-hash
	}
)

@endpoint-type < #server #client #source #sink >
