all:
	@ cd library; make
	@ cd wrapper; make
	@ cd utils; make
	@ cd tools; make

install:
	@ cd idl; make install
	@ cd library; make install
	@ cd wrapper; make install
	@ cd utils; make install
	@ cd tools; make install
	@ cd docs; make install

clean:
	@ cd library; make clean
	@ cd wrapper; make clean
	@ cd utils; make clean
	@ cd tools; make clean
	@ cd docs; make clean
	rm -f .prefix

reallyclean:
	@ cd docs; make clean
